version: "2"
services:
    chat:
        build:
            context: ./lets-chat
            dockerfile: Dockerfile
        image: lets_chat_image
        restart: always
        environment:
            - task_name=test
        volumes:
            - "./LocalStorage/worker:/app/LocalStorage"
        depends_on:
            - mongo

    mongo:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: wulab
            MONGO_INITDB_ROOT_PASSWORD: wulab
        volumes:
            - "./mongo_db_docker/configdb:/data/configdb"
            - "./mongo_db_docker/db:/data/db"
        ports:
            - 27017:27017
    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 20002:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: wulab
            ME_CONFIG_MONGODB_ADMINPASSWORD: wulab
            ME_CONFIG_MONGODB_URL: mongodb://wulab:wulab@mongo:27017/